site_name: Philly Community Wireless Docs
site_url: https://docs.phillycommunitywireless.org/en/latest/

theme:
  name: material
  language: en
  logo: assets/icons/logo.svg
  favicon: assets/icons/favicon/favicon.ico
  custom_dir: overrides
  features:
    # Enable this if searching ever becomes slow
    # - navigation.instant
    - navigation.tracking
    - navigation.sections
  palette:
    # Dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

# extra:
#  homepage: https://phillycommunitywireless.org
#  alternate:
#    - name: English
#      link: /en/latest
#      lang: en

#    - name: Espa√±ol
#      link: /es/latest
#      lang: es

markdown_extensions:
  - meta
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
